---
title: "My Portfolio"
---

Hello!

This website hosts my [portfolio](https://datascience4psych.github.io/DataScience4Psych/guidance.html#portfolio) and [accompanying documentation](https://datascience4psych.github.io/DataScience4Psych/guidance.html#documenting-your-project) that I developed as part of [Data Science for Psychologists](https://datascience4psych.github.io/DataScience4Psych/). You can find the links to individual portfolio pieces in the header or down below. Each piece has a description of my goal for the piece, the product (computer program, hand graph, computer graph, etc.), the data, and some interpretation. I encourage you to explore them.


### List of Portfolio Pieces

#### [Piece 1: Trajectories and Variations of Family Decision Making in the United States](p01.html)

#### [Piece 2: Tragectories and Variations of Family Decision Making Across Countries](p02.html)

#### [Piece 3: Creating a Monte Carlo Simulation](p03.html)

#### [Piece 4: Tinkering Around Tidy Tuesday](p04.html)

#### [Piece 5: ~ Under Construction ~](p05.html)

#### [Piece 6: R Code Cheatsheet](p06.html)

#### [Piece 7: Evaluation and tips for Lab 9](p07.html)

#### [Piece 8: Simulating Data](p08.html)

#### [Piece 9: ChatGPT - Is It Helpful?](p09.html)

#### [Piece 10: ~ Under Construction ~](p10.html)

